// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsFfW0tapuSFkAGoWq9_kLH2osQUv_y1w',
    appId: '1:495764425049:web:4487f0c058e896fdc1a448',
    messagingSenderId: '495764425049',
    projectId: 'flutterfiretest-dcf58',
    authDomain: 'flutterfiretest-dcf58.firebaseapp.com',
    storageBucket: 'flutterfiretest-dcf58.firebasestorage.app',
    measurementId: 'G-0QC7PN9RDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcvK8fN8uK2G7zmcgD49GVtjzkE4cb53w',
    appId: '1:495764425049:android:03df899aaa9cf068c1a448',
    messagingSenderId: '495764425049',
    projectId: 'flutterfiretest-dcf58',
    storageBucket: 'flutterfiretest-dcf58.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsFfW0tapuSFkAGoWq9_kLH2osQUv_y1w',
    appId: '1:495764425049:web:9346e933919ef06fc1a448',
    messagingSenderId: '495764425049',
    projectId: 'flutterfiretest-dcf58',
    authDomain: 'flutterfiretest-dcf58.firebaseapp.com',
    storageBucket: 'flutterfiretest-dcf58.firebasestorage.app',
    measurementId: 'G-CVM2H05VQP',
  );

}